/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface joiSchema {
  /**
   * @example 0.07
   */
  average?: number;
  companies?: {
    /**
     * @example TWD
     */
    currency?: string;
    /**
     * @example 0.1302
     */
    estimate?: number;
    /**
     * @example 2023-09-30
     */
    fiscalDateEnding?: string;
    /**
     * @example ASE Technology Holding Co.Ltd
     */
    name?: string;
    /**
     * @example 2023-11-02
     */
    reportDate?: string;
    /**
     * @example ASX
     */
    symbol?: string;
  }[];
  /**
   * @example USD
   */
  targetCurrency?: string;
}
